general:  # General server settings.
  host: http://localhost:8080
  privateKeyPath: jwt/private.pem 
  publicKeyPath: jwt/public.pem
  issuer: http://localhost:8080   
  algorithm: auto

adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD

storage:
  appStorage:
    type: dynamodb
    region: us-east-1
  userStorage:
    type: dynamodb
    region: us-east-1
  tokenStorage:
    type: dynamodb
    region: us-east-1
  tokenBlacklist:
    type: dynamodb
    region: us-east-1
  verificationCodeStorage:
    type: dynamodb
    region: us-east-1

sessionStorage: 
  type: dynamodb
  region: us-east-1
  sessionDuration: 300

# If using Identifo as AWS Lambda, we cannot update config file,
# as Lambda environment is a read-only one. That's why we must
# store configuration file in, for example, S3 bucket.
# AWS Access Key, Secret Access Key, and bucket name must be stored
# in environment variables.
configurationStorage:
  type: s3
  settingsKey: server-config.yaml
  region: us-east-1

staticFiles:
  serverConfigPath: server-config.yaml
  staticFolderPath: ./static
  emailTemplatesPath: ./email_templates
  emailTemplateNames:
    welcome: welcome.html
    resetPassword: reset_password.html
    invite: invite_email.html
    verify: verify_email.html
    tfa: tfa_email.html
  adminPanelBuildPath: ./admin_panel/build

login:
  loginWith:
    phone: true
    username: true
    federated: true
  tfaType: app

externalServices: 
  mailService: aws ses 
  smsService:
    type: mock