# This file is needed to define the configuration storage of a server.

location: local # Can be 'local', 'etcd', or 's3'.
folder: # Folder that contains server configuration file, when type is 'local' or 's3'. Assumed to be root if ommitted.
filename: server-config.yaml # Name of a server configuration file, when type is 'local' or 's3'.
bucket: # Bucket with server configuration when type is 's3'.
region: # Region for the bucket when type is 's3'.
key: # Key for the server settings if type is 'etcd'.
endpoints: # Etcd-related setting.