host: http://localhost:8080

pemFolderPath: ../../jwt
privateKey: private.pem
publicKey: public.pem
issuer: http://localhost:8080
algorithm: auto

mailService: aws ses
sessionStorage:
  type: memory
  sessionDuration: 300

configurationStorage:
  type: file
  settingsKey: identifo/server-settings

smsService:
  type: mock

loginWith:
  phone: true
  username: true
  federated: true

adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD

serverConfigPath: ./server-config.yaml

storage:
  appStorage:
    type: boltdb
    path: ./db.db
  userStorage:
    type: boltdb
    path: ./db.db
  tokenStorage:
    type: boltdb
    path: ./db.db
  verificationCodeStorage:
    type: boltdb
    path: ./db.db

staticFolderPath: ../../static
emailTemplatesPath: ../../email_templates
emailTemplateNames:
  welcome: welcome.html
  resetPassword: reset_password.html
  inviteEmail: invite_email.html
  verifyEmail: verify_email.html
