general:
  host: http://localhost:8081
  privateKeyPath: ../../jwt/private.pem
  publicKeyPath: ../../jwt/public.pem
  issuer: http://localhost:8081
  algorithm: auto

adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD

storage:
  appStorage:
    type: boltdb
    path: ./db.db
  userStorage:
    type: boltdb
    path: ./db.db
  tokenStorage:
    type: boltdb
    path: ./db.db
  tokenBlacklist:
    type: boltdb
    path: ./db.db
  verificationCodeStorage:
    type: boltdb
    path: ./db.db

sessionStorage:
  type: memory
  sessionDuration: 300

configurationStorage:
  type: file
  settingsKey: server-config.yaml

staticFiles:
  serverConfigPath: server-config.yaml
  staticFolderPath: ../../web/static   # Folder for the static files.
  emailTemplatesPath: ../../email_templates
  emailTemplateNames: 
    welcome: welcome.html
    resetPassword: reset_password.html
    invite: invite_email.html
    verify: verify_email.html
    tfa: tfa_email.html
  appleDomainAssociation: apple-developer-domain-association.txt
  adminPanelBuildPath: ../../admin_panel/build

login:
  loginWith:
    phone: true
    username: true
    federated: true
  tfaType: app

externalServices: 
  mailService: mock
  smsService:
    type: mock
