general:
  host: http://localhost:8081
  issuer: http://localhost:8081
  algorithm: auto

adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD

storage:
  appStorage:
    type: boltdb
    path: ./db.db
  userStorage:
    type: boltdb
    path: ./db.db
  tokenStorage:
    type: boltdb
    path: ./db.db
  tokenBlacklist:
    type: boltdb
    path: ./db.db
  verificationCodeStorage:
    type: boltdb
    path: ./db.db

sessionStorage:
  type: memory
  sessionDuration: 300

configurationStorage:
  type: file
  settingsKey: server-config.yaml
  keyStorage: # Storage for keys used for signing and verifying JWTs.
    type: file # Key storage type. Supported values are "file" and "s3".
    # Key names.
    # If type is file, must be a filepath (e.g, jwt/public.pem).
    # If type is s3, must be a name of an object in the bucket (e.g, public.pem).
    publicKey: ../../jwt/public.pem
    privateKey: ../../jwt/private.pem
    region: # S3-related setting.


staticFiles:
  serverConfigPath: server-config.yaml
  staticFolderPath: ../../web/static   # Folder for the static files.
  emailTemplatesPath: ../../email_templates
  adminPanelBuildPath: ../../admin_panel/build
  apple:
    developerDomainAssociation: apple/apple-developer-domain-association.txt
    appSiteAssociation: apple/apple-app-site-association

login:
  loginWith:
    phone: true
    username: true
    federated: true
  tfaType: app

externalServices: 
  emailService:
    type: mock
    domain:
    privateKey:
    publicKey:
    sender:
    region: 
  smsService:
    type: mock
