general:
  host: http://localhost:8081
  issuer: http://localhost:8081
  algorithm: auto

adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD

storage:
  appStorage:
    type: boltdb
    path: ./db.db
  userStorage:
    type: boltdb
    path: ./db.db
  tokenStorage:
    type: boltdb
    path: ./db.db
  tokenBlacklist:
    type: boltdb
    path: ./db.db
  verificationCodeStorage:
    type: boltdb
    path: ./db.db

sessionStorage:
  type: memory
  sessionDuration: 300

configurationStorage:
  type: file
  settingsKey: server-config.yaml
  keyStorage: # Storage for keys used for signing and verifying JWTs.
    type: local # Key storage type. Supported values are "local" and "s3".
    folder: ../../test # Folder for public.pem and private.pem keys. Assumed to be root if ommitted.
    bucket: # S3-related setting. If "IDENTIFO_JWT_KEYS_BUCKET" env variable is set, it overrides the value specified here.
    region: # Required if type is 's3'.

staticFilesStorage:
  type: local # Supported values are "local", "s3", and "dynamodb".
  serverConfigPath: server-config.yaml  # Path to the file with server settings.
  folder: ../../static # Folder for static files. All following paths are relative to this location. Assumed to be root if ommitted.
  bucket: # Bucket which contains static files if type is "s3". If "IDENTIFO_STATIC_FILES_BUCKET" env variable is set, it overrides the value specified here.
  region: # Required when type is "s3" or "dynamodb".
  endpoint: # DynamoDB-specific setting. Can be ommitted when region is set.
  serveAdminPanel: true # If ommited or set to false, adminpanel router won't be initialized.

login:
  loginWith:
    phone: true
    username: true
    federated: true
  tfaType: email

externalServices: 
  emailService:
    type: mock
    domain:
    privateKey:
    publicKey:
    sender:
    region: 
  smsService:
    type: mock
