host: http://localhost:8080

pemFolderPath: ./pem
privateKey: private.pem
publicKey: public.pem
issuer: http://localhost:8080

algorithm: auto
mailService: aws ses
sessionStorage: memory
sessionDuration: 300

configurationStorage: mock
settingsKey: identifo/server-settings

staticFolderPath: ./static
emailTemplatesPath: ./email_templates
emailTemplateNames:
  welcome: welcome.html
  resetPassword: reset_password.html
  inviteEmail: invite_email.html
  verifyEmail: verify_email.html

smsService: mock
twilio:
  accountSid:
  authToken:
  serviceSid:

adminAccountSettings:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD

serverConfigPath: ./server-config.yaml

dbType: boltdb
dbPath: db.db
