general:
  host: http://localhost:8081
  issuer: http://localhost:8081
  algorithm: auto

adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD

storage:
  appStorage:
    type: boltdb
    path: ./db.db
  userStorage:
    type: boltdb
    path: ./db.db
  tokenStorage:
    type: boltdb
    path: ./db.db
  tokenBlacklist:
    type: boltdb
    path: ./db.db
  verificationCodeStorage:
    type: boltdb
    path: ./db.db

sessionStorage:
  type: memory
  sessionDuration: 300

configurationStorage:
  type: file
  settingsKey: server-config.yaml
  keyStorage: # Storage for keys used for signing and verifying JWTs.
    type: file # Key storage type. Supported values are "file" and "s3".
    # Key names.
    # If type is file, must be a filepath (e.g, jwt/public.pem).
    # If type is s3, must be a name of an object in the bucket (e.g, public.pem).
    publicKey: ../../jwt/public.pem
    privateKey: ../../jwt/private.pem
    region: # S3-related setting.


staticFilesStorage:
  type: local # Supported values are "local" and "s3".
  serverConfigPath: server-config.yaml  # Path to the file with server settings.
  # Location for static files. If type is local, it is a folder. If type is s3, must be a bucket name.
  # If type is s3 and "IDENTIFO_STATIC_FILES_BUCKET" env variable is set, it overrides the value specified here.
  staticFilesLocation: ./static   # All following paths are relative to this location.
  region: # S3-specific setting. Needed when type is s3.
  pagesPath: ./html # Folder for html pages.
  emailTemplatesPath: ./email_templates # Folder for the email templates.
  appleFilesPath: ./apple # Folder for the Apple-related files.
  serveAdminPanel: true # If ommited or set to false, adminpanel router won't be initialized.

login:
  loginWith:
    phone: true
    username: true
    federated: true
  tfaType: app

externalServices: 
  emailService:
    type: mock
    domain:
    privateKey:
    publicKey:
    sender:
    region: 
  smsService:
    type: mock
