host: http://localhost:8080

pemFolderPath: ./pem
privateKey: private.pem
publicKey: public.pem
issuer: http://localhost:8080

algorithm: auto
mailService: aws ses
sessionStorage: memory
sessionDuration: 300

staticFolderPath: ./static
emailTemplatesPath: ./email_templates
emailTemplateNames:
  welcome: welcome.html
  resetPassword: reset_password.html
  inviteEmail: invite_email.html
  verifyEmail: verify_email.html

smsService: mock
twilio:
  accountSid:
  authToken:
  serviceSid:

accountConfigPath: ./account-config.yaml
serverConfigPath: ./server-config.yaml

dbType: boltdb
dbPath: db.db
