host: http://localhost:8080

pemFolderPath: ./pem
privateKey: private.pem
publicKey: public.pem
issuer: http://localhost:8080
algorithm: auto

mailService: aws ses
sessionStorage:
  type: memory
  sessionDuration: 300

configurationStorage:
  type: mock
  settingsKey: identifo/server-settings

smsService:
  type: mock

adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD

serverConfigPath: ./server-config.yaml

database:
  dbType: boltdb
  dbPath: db.db

staticFolderPath: ./static
emailTemplatesPath: ./email_templates
emailTemplateNames:
  welcome: welcome.html
  resetPassword: reset_password.html
  inviteEmail: invite_email.html
  verifyEmail: verify_email.html
