version: "3"
services:
  identifo:
    image: identifo:latest
    build: .
    environment:
      - IDENTIFO_ADMIN_LOGIN=admin@admin.com
      - IDENTIFO_ADMIN_PASSWORD=password
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - identifo
    volumes:
      - ./server-config.yaml:/root/server-config.yaml
      - ./jwt/test_artifacts:/root/jwt/test_artifacts
      - ./static/:/root/static/
      - ./db.db:/root/db.db
networks:
  identifo:
