version: "3"
services:
  identifo:
    image: identifo:latest
    build: .
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - identifo
    volumes:
      - ./server-config-dev.yaml:/root/server-config.yaml
      - ./jwt/test_artifacts:/root/jwt/
      - ./static/:/root/static/

networks:
  identifo:
