version: "3"
services:
  identifo:
    image: identifo:latest
    build: .
    env_file:
      - .env
    ports:
      - "8111:8080"
    networks:
      - identifo
    volumes:
      - ./server-config.yaml:/root/server-config.yaml

networks:
  identifo:
