general:
  host: http://localhost:8081
  issuer: http://localhost:8081
  algorithm: auto
adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD
storage:
  appStorage:
    type: boltdb
    name: identifo
    endpoint: mongodb://localhost:27017
    region: us-east-2
    path: ./db.db
  userStorage:
    type: boltdb
    name: identifo
    endpoint: mongodb://localhost:27017
    region: us-east-2
    path: ./db.db
  tokenStorage:
    type: boltdb
    name: identifo
    endpoint: mongodb://localhost:27017
    region: us-east-2
    path: ./db.db
  tokenBlacklist:
    type: boltdb
    name: identifo
    endpoint: mongodb://localhost:27017
    region: us-east-2
    path: ./db.db
  verificationCodeStorage:
    type: boltdb
    name: identifo
    endpoint: mongodb://localhost:27017
    region: us-east-2
    path: ./db.db
  inviteStorage:
    type: boltdb
    name: identifo
    endpoint: mongodb://localhost:27017
    region: us-east-2
    path: ./db.db
sessionStorage:
  type: memory
  sessionDuration: 300
staticFilesStorage:
  type: local
  serverConfigPath: server-config.yaml
  folder: ./static
  serveAdminPanel: true
  serveNewWeb: true
externalServices:
  emailService:
    type: mock
  smsService:
    type: mock
login:
  loginWith:
    username: true
    phone: true
    federated: true
  tfaType: app
keyStorage:
  type: local
  file:
    private_key_path: ./jwt/test_artifacts/private.pem
    public_key_path: ./jwt/test_artifacts/public.pem
