general: # General server settings.
  port: 8081
  host: http://localhost:8081 # Identifo server URL. If "HOST_NAME" env variable is set, it overrides the value specified here.
  issuer: http://localhost:8081 # JWT tokens issuer.
  algorithm: es256 # Algorithm for the token service. Supported values are: "rs256", "es256" and "auto".

# Names of environment variables that store admin credentials.
adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD

# Storage settings holds together all storage settings.
# All settings for particular database engine (i.e, filepaths for BoltDB,
# endpoints and regions for DynamoDB etc.) are assumed to be the same across
# all storages. If they are not the same, the latest option in this file will be applied.
# For example, if there are two MongoDB-backed storages, appStorage and tokenStorage,
# and endpoint for appStorage is localhost:27017, while tokenStorage's endpoint is localhost:27018,
# server will connect both storages to localhost:27018.
storage:
  appStorage: &storage_settings
    type: boltdb
    boltdb:
      path: ./db.db
  userStorage: *storage_settings
  tokenStorage: *storage_settings
  tokenBlacklist: *storage_settings
  verificationCodeStorage: *storage_settings
  inviteStorage: *storage_settings

# Storage for admin sessions.
sessionStorage:
  type: memory # Supported values are "memory", "redis", and "dynamodb".
  # Admin session duration in seconds.
  # This value specifies the maximum time of inactivity in the admin panel before asking to relogin.
  sessionDuration: 300
  address: # Redis-related setting.
  password: # Redis-related setting.
  db: # Redis-related setting.
  region: # DynamoDB-related setting.
  endpoint: # DynamoDB-related setting. Can be figured out automatically from the region.

keyStorage: # Storage for keys used for signing and verifying JWTs.
  type: local # Key storage type. Supported values are "local" and "s3".
  #file/local key storage settings
  file:
    private_key_path: ./jwt/test_artifacts/private.pem
    public_key_path: ./jwt/test_artifacts/public.pem

static:
  type: local
  local:
    folder: ./static
  serveAdminPanel: true

login: # Supported login ways.
  loginWith:
    phone: true
    email: true
    username: true
    federated: true
  # Type of two-factor authentication, if application enables it.
  # Supported values are: "app" (like Google Authenticator), "sms", "email".
  tfaType: app

services:
  email: # Email service settings.
    type: mock # Supported values are "mailgun", "aws ses", and "mock".
    # mailgun:
    #   domain: identifo.com # Mailgun related setting. If "MAILGUN_DOMAIN" env variable is set, it overrides the value specified here.
    #   privateKey: ABXCDS # Mailgun-related setting. If "MAILGUN_PRIVATE_KEY" env variable is set, it overrides the value specified here.
    #   publicKey: AAABBBDDD # Mailgun-related setting. If "MAILGUN_PUBLIC_KEY" env variable is set, it overrides the value specified here.
    #   sender: admin@admin.com # Sender of the emails. If "MAILGUN_SENDER" or "AWS_SES_SENDER" env variable is set, it overrides (depending on the email service type) the value specified here.
    # ses:
    #   sender: admin@admin.com # Sender of the emails. If "MAILGUN_SENDER" or "AWS_SES_SENDER" env variable is set, it overrides (depending on the email service type) the value specified here.
    #   region: es-east1 # AWS SES-related setting. If "AWS_SES_REGION" env variable is set, it overrides the value specified here.
  sms: # SMS service settings.
    type: mock # Supported values are: "twilio", "nexmo", "routemobile", "mock".
    # twilio:
    #   accountSid: SID1234 # Twilio-related setting.
    #   authToken: TOKENABCDS # Twilio-related setting.
    #   serviceSid: SIDFFFF # Twilio-related setting.
    # nexmo:
    #   apiKey: KEY1234 # Nexmo-related setting.
    #   apiSecret: SECRET4433 # Nexmo-related setting.
    # routemobile:
    #   username: identifo # RouteMobile-related setting.
    #   password: secret # RouteMobile-related setting.
    #   source: whatever # RouteMobile-related setting.
    #   region: australia # RouteMobile-related setting. Supported values are: uae.
