export const FETCH_SERVER_SETTINGS = 'FETCH_SERVER_SETTINGS';
export const UPDATE_SERVER_SETTINGS = 'UPDATE_SERVER_SETTINGS';

export const FETCH_JWT_KEYS = 'FETCH_JWT_KEYS';
export const SET_VERIFICATION_STATUS = 'SET_VERIFICATION_STATUS';
