version: "2"
services:
    dynamodb:
      image: amazon/dynamodb-local:latest
      ports:
        - "8000:8000"
    admin:
      image: aaronshaf/dynamodb-admin:latest
      ports:
        - "8001:8001"
      environment:
        - DYNAMO_ENDPOINT=dynamodb:8000
