const types = {
  FETCH_USERS_ATTEMPT: 'FETCH_USERS_ATTEMPT',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',

  POST_USER_ATTEMPT: 'POST_USER_ATTEMPT',
  POST_USER_SUCCESS: 'POST_USER_SUCCESS',
  POST_USER_FAILURE: 'POST_USER_FAILURE',

  ALTER_USER_ATTEMPT: 'ALTER_USER_ATTEMPT',
  ALTER_USER_SUCCESS: 'ALTER_USER_SUCCESS',
  ALTER_USER_FAILURE: 'ALTER_USER_FAILURE',

  FETCH_USER_BY_ID_ATTEMPT: 'FETCH_USER_BY_ID_ATTEMPT',
  FETCH_USER_BY_ID_SUCCESS: 'FETCH_USER_BY_ID_SUCCESS',
  FETCH_USER_BY_ID_FAILURE: 'FETCH_USER_BY_ID_FAILURE',

  DELETE_USER_BY_ID_ATTEMPT: 'DELETE_USER_BY_ID_ATTEMPT',
  DELETE_USER_BY_ID_SUCCESS: 'DELETE_USER_BY_ID_SUCCESS',
  DELETE_USER_BY_ID_FAILURE: 'DELETE_USER_BY_ID_FAILURE',

  RESET_USER_ERROR: 'RESET_USER_ERROR',
};

export default types;
