// Code generated by "message_const_generator"; DO NOT EDIT.

package localization

const (

	//===========================================================================
	//  test messages
	//===========================================================================
	// Test ->  I am test string
	Test = "test"
	// KeyWithSpaces ->  key with spaces passed test
	KeyWithSpaces = "key with spaces"

	//===========================================================================
	//  api messages
	//===========================================================================
	// ApiInternalServerError ->  Internal server error.
	ApiInternalServerError = "api.internal_server_error"
	// ApiAppAccessDenied ->  Access denied.
	ApiAppAccessDenied = "api.app.access_denied"
	// ErrorApiUserUnableToCreate ->  Unable to create use, please try again or contact support team.
	ErrorApiUserUnableToCreate = "error.api.user.unable_to_create"
	// ErrorApiVerificationCodeInvalid ->  Sorry, the code you entered is invalid or has expired. Please get a new one.
	ErrorApiVerificationCodeInvalid = "error.api.verification_code.invalid"
	// ErrorApiUserNotFound ->  User not found.
	ErrorApiUserNotFound = "error.api.user.not_found"
	// ErrorApiUsernameTaken ->  Username is taken. Try to choose another one.
	ErrorApiUsernameTaken = "error.api.username.taken"
	// ErrorApiUsernamePhoneEmailTaken ->  Username, email or/and phone is taken. Try to choose another one.
	ErrorApiUsernamePhoneEmailTaken = "error.api.username_phone_email.taken"
	// ErrorApiEmailTaken ->  Email is taken. Try to choose another one.
	ErrorApiEmailTaken = "error.api.email.taken"
	// ErrorApiPhoneTaken ->  Phone is taken. Try to choose another one.
	ErrorApiPhoneTaken = "error.api.phone.taken"
	// ErrorApiInviteTokenServerError ->  Unable to create invite token. Try again or contact support team.
	ErrorApiInviteTokenServerError = "error.api.invite_token.server_error"
	// ErrorApiInviteUnableToInvalidate ->  Unable to invalidate invite. Try again or contact support team.
	ErrorApiInviteUnableToInvalidate = "error.api.invite.unable_to_invalidate"
	// ErrorApiInviteUnableToSave ->  Unable to save invite. Try again or contact support team.
	ErrorApiInviteUnableToSave = "error.api.invite.unable_to_save"
	// ErrorsApiInviteUnableToGet ->  Unable to get invites. Try again or contact support team.
	ErrorsApiInviteUnableToGet = "errors.api.invite.unable_to_get"
	// ErrorApiEmailNotSent ->  Unable to send email. Try again or contact support team.
	ErrorApiEmailNotSent = "error.api.email.not_sent"
	// ErrorApiRequestPasswordWeak ->  Password is not strong enough.
	ErrorApiRequestPasswordWeak = "error.api.request.password.weak"
	// ErrorApiRequestIncorrectLoginOrPassword ->  Incorrect email or password.
	ErrorApiRequestIncorrectLoginOrPassword = "error.api.request.incorrect_login_or_password"
	// ErrorApiRequestScopesForbidden ->  Requested scopes are forbidden.
	ErrorApiRequestScopesForbidden = "error.api.request.scopes.forbidden"
	// ErrorApiRequestBodyInvalid ->  Invalid or empty input data.
	ErrorApiRequestBodyInvalid = "error.api.request.body.invalid"
	// ErrorApiRequestBodyParamsInvalid ->  Input data does not pass validation. Please check you data.
	ErrorApiRequestBodyParamsInvalid = "error.api.request.body.params.invalid"
	// ErrorApiRequestBodyOldpasswordInvalid ->  Old password is invalid. Please check it and try again.
	ErrorApiRequestBodyOldpasswordInvalid = "error.api.request.body.oldpassword.invalid"
	// ErrorApiRequestBodyEmailInvalid ->  Specified email is invalid or empty.
	ErrorApiRequestBodyEmailInvalid = "error.api.request.body.email.invalid"
	// ErrorApiRequestSignatureInvalid ->  Incorrect or empty request signature.
	ErrorApiRequestSignatureInvalid = "error.api.request.signature.invalid"
	// ErrorApiRequestAppIdInvalid ->  Incorrect or empty application ID.
	ErrorApiRequestAppIdInvalid = "error.api.request.app_id.invalid"
	// ErrorApiRequestCallbackurlInvalid ->  Please add callbackURL in application settings.
	ErrorApiRequestCallbackurlInvalid = "error.api.request.callbackurl.invalid"
	// ErrorApiRequestTokenInvalid ->  Incorrect or empty Bearer token.
	ErrorApiRequestTokenInvalid = "error.api.request.token.invalid"

	//===========================================================================
	//  2FA errors
	//===========================================================================
	// ErrorApiRequest2FaCodeEmpty ->  Empty two-factor authentication code.
	ErrorApiRequest2FaCodeEmpty = "error.api.request.2fa_code.empty"
	// ErrorApiRequest2FaCodeInvalid ->  Invalid two-factor authentication code.
	ErrorApiRequest2FaCodeInvalid = "error.api.request.2fa_code.invalid"
	// ErrorApiRequest2FaAlreadyEnabled ->  Two-factor authentication already enabled.
	ErrorApiRequest2FaAlreadyEnabled = "error.api.request.2fa.already_enabled"
	// ErrorApiRequest2FaPleaseEnable ->  Please enable two-factor authentication.
	ErrorApiRequest2FaPleaseEnable = "error.api.request.2fa.please_enable"
	// ErrorApiRequest2FaPleaseDisable ->  Please disable two-factor authentication.
	ErrorApiRequest2FaPleaseDisable = "error.api.request.2fa.please_disable"
	// ErrorApiRequest2FaMandatory ->  Two-factor authentication is required for this app.
	ErrorApiRequest2FaMandatory = "error.api.request.2fa.mandatory"
	// ErrorApiRequest2FaDisabled ->  Two-factor authentication is disabled for this app.
	ErrorApiRequest2FaDisabled = "error.api.request.2fa.disabled"
	// ErrorApiRequest2FaSetPhone ->  Please specify your phone number to be able to receive one-time passwords.
	ErrorApiRequest2FaSetPhone = "error.api.request.2fa.set_phone"
	// ErrorApiRequest2FaSetEmail ->  Please specify your email address to be able to receive one-time passwords.
	ErrorApiRequest2FaSetEmail = "error.api.request.2fa.set_email"
	// ErrorApiRequestEnable2FaEmptyPhoneAndEmail ->  Phone and email are empty.
	ErrorApiRequestEnable2FaEmptyPhoneAndEmail = "error.api.request.enable_2fa.empty_phone_and_email"
	// ErrorApiRequest2FaUnableToSendOtp ->  Error sending OTP code with SMS or Email.
	ErrorApiRequest2FaUnableToSendOtp = "error.api.request.2fa.unable_to_send_OTP"

	//===========================================================================
	//  App errors
	//===========================================================================
	// ErrorApiAppInactive ->  The app is inactive.
	ErrorApiAppInactive = "error.api.app.inactive"
	// ErrorApiAppRegistrationForbidden ->  Registration in this app is forbidden.
	ErrorApiAppRegistrationForbidden = "error.api.app.registration_forbidden"
	// ErrorApiAppUnableToCreateResetToken ->  Error creating reset token.
	ErrorApiAppUnableToCreateResetToken = "error.api.app.unable_to_create_reset_token"
	// ErrorApiAppUnableToCreateAccessToken ->  Error creating access token.
	ErrorApiAppUnableToCreateAccessToken = "error.api.app.unable_to_create_access_token"
	// ErrorApiAppUnableToCreateRefreshToken ->  Error creating refresh token.
	ErrorApiAppUnableToCreateRefreshToken = "error.api.app.unable_to_create_refresh_token"
	// ErrorApiRequestTokenSub ->  Unable to extract Subject claim from the token.
	ErrorApiRequestTokenSub = "error.api.request.token.sub"
	// ErrorApiRequestAuthorizerInternalInit ->  Error creating authz service.
	ErrorApiRequestAuthorizerInternalInit = "error.api.request.authorizer.internal.init"

	//===========================================================================
	//  Federated login
	//===========================================================================
	// ApiAppFederatedProviderNotSupported ->  Federated provider is not supported.
	ApiAppFederatedProviderNotSupported = "api.app.federated.provider.not_supported"
	// ApiAppFederatedProviderEmptyRedirect ->  Empty redirect URL.
	ApiAppFederatedProviderEmptyRedirect = "api.app.federated.provider.empty_redirect"
	// ApiAppFederatedProviderEmpty ->  Empty federated login provider.
	ApiAppFederatedProviderEmpty = "api.app.federated.provider.empty"
	// ApiAppFederatedProviderCantComplete ->   Unable to complete federated login.
	ApiAppFederatedProviderCantComplete = "api.app.federated.provider.cant_complete"
	// ApiAppUsernameLoginNotSupported ->  Login with username is not supported by app.
	ApiAppUsernameLoginNotSupported = "api.app.username.login.not_supported"
	// ApiAppPhoneLoginNotSupported ->  Login with phone number is not supported by app.
	ApiAppPhoneLoginNotSupported = "api.app.phone.login.not_supported"
	// ErrorApiUnableToInitializeIdentifo ->  Unable to initialize NativeLogin.
	ErrorApiUnableToInitializeIdentifo = "error.api.unable_to_initialize_identifo"
)
