const types = {
  FETCH_APPLICATIONS_ATTEMPT: 'FETCH_APPLICATIONS_ATTEMPT',
  FETCH_APPLICATIONS_SUCCESS: 'FETCH_APPLICATIONS_SUCCESS',
  FETCH_APPLICATIONS_FAILURE: 'FETCH_APPLICATIONS_FAILURE',

  POST_APPLICATION_ATTEMPT: 'POST_APPLICATION_ATTEMPT',
  POST_APPLICATION_SUCCESS: 'POST_APPLICATION_SUCCESS',
  POST_APPLICATION_FAILURE: 'POST_APPLICATION_FAILURE',

  DELETE_APPLICATION_ATTEMPT: 'DELETE_APPLICATION_ATTEMPT',
  DELETE_APPLICATION_SUCCESS: 'DELETE_APPLICATION_SUCCESS',
  DELETE_APPLICATION_FAILURE: 'DELETE_APPLICATION_FAILURE',

  ALTER_APPLICATION_ATTEMPT: 'ALTER_APPLICATION_ATTEMPT',
  ALTER_APPLICATION_SUCCESS: 'ALTER_APPLICATION_SUCCESS',
  ALTER_APPLICATION_FAILURE: 'ALTER_APPLICATION_FAILURE',

  FETCH_APPLICATION_BY_ID_ATTEMPT: 'FETCH_APPLICATION_BY_ID_ATTEMPT',
  FETCH_APPLICATION_BY_ID_SUCCESS: 'FETCH_APPLICATION_BY_ID_SUCCESS',
  FETCH_APPLICATION_BY_ID_FAILURE: 'FETCH_APPLICATION_BY_ID_FAILURE',

  FETCH_FEDERATED_PROVIDERS_ATTEMTP: 'FETCH_FEDERATED_PROVIDERS_ATTEMTP',
  FETCH_FEDERATED_PROVIDERS_SUCCESS: 'FETCH_FEDERATED_PROVIDERS_SUCCESS',
  FETCH_FEDERATED_PROVIDERS_FAILURE: 'FETCH_FEDERATED_PROVIDERS_FAILURE',

  RESET_APPLICATION_ERROR: 'RESET_APPLICATION_ERROR',
};

export default types;
