const types = {
  TEST_CONNECTION_ATTEMPT: 'TEST_CONNECTION_ATTEMPT',
  TEST_CONNECTION_SUCCESS: 'TEST_CONNECTION_SUCCESS',
  TEST_CONNECTION_FAILURE: 'TEST_CONNECTION_FAILURE',

  FETCH_DB_SETTINGS_ATTEMPT: 'FETCH_DB_SETTINGS_ATTEMPT',
  FETCH_DB_SETTINGS_SUCCESS: 'FETCH_DB_SETTINGS_SUCCESS',
  FETCH_DB_SETTINGS_FAILURE: 'FETCH_DB_SETTINGS_FAILURE',

  POST_DB_SETTINGS_ATTEMPT: 'POST_DB_SETTINGS_ATTEMPT',
  POST_DB_SETTINGS_SUCCESS: 'POST_DB_SETTINGS_SUCCESS',
  POST_DB_SETTINGS_FAILURE: 'POST_DB_SETTINGS_FAILURE',

  RESET_DB_SETTINGS_ERROR: 'RESET_DB_SETTINGS_ERROR',
};

export default types;
