const types = {
  TEST_CONNECTION_ATTEMPT: 'TEST_CONNECTION_ATTEMPT',
  TEST_CONNECTION_SUCCESS: 'TEST_CONNECTION_SUCCESS',
  TEST_CONNECTION_FAILURE: 'TEST_CONNECTION_FAILURE',

  POST_DB_SETTINGS_ATTEMPT: 'POST_DB_SETTINGS_ATTEMPT',
  POST_DB_SETTINGS_SUCCESS: 'POST_DB_SETTINGS_SUCCESS',
  POST_DB_SETTINGS_FAILURE: 'POST_DB_SETTINGS_FAILURE',

  RESET_DB_SETTINGS_ERROR: 'RESET_DB_SETTINGS_ERROR',
  RESET_CONNECTION_STORE: 'RESET_CONNECTION_STORE',
};

export default types;
