const types = {
  TEST_CONNECTION_ATTEMPT: 'TEST_CONNECTION_ATTEMPT',
  TEST_CONNECTION_SUCCESS: 'TEST_CONNECTION_SUCCESS',
  TEST_CONNECTION_FAILURE: 'TEST_CONNECTION_FAILURE',

  RESET_DB_SETTINGS_ERROR: 'RESET_DB_SETTINGS_ERROR',
  RESET_CONNECTION_STORE: 'RESET_CONNECTION_STORE',
};

export default types;
