general:
  host: http://localhost:8081
  port: "8081"
  issuer: http://localhost
  supported_scopes: []
adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD
storage:
  appStorage: &storage_settings
    type: boltdb
    boltdb:
      path: ./db.db
  userStorage:
    type: plugin
    plugin:
      cmd: ./plugins/bin/bolt-user-storage
      params: { "path": "./db_plugin.db" }
      redirectStd: true
  tokenStorage: *storage_settings
  tokenBlacklist: *storage_settings
  verificationCodeStorage: *storage_settings
  inviteStorage: *storage_settings
  managementKeysStorage: *storage_settings
sessionStorage:
  type: memory
  sessionDuration: 300
  redis:
    address: ""
    password: ""
    db: 0
    cluster: false
    prefix: ""
  dynamo:
    region: ""
    endpoint: ""
services:
  email:
    type: mock
    mailgun:
      domain: ""
      privateKey: ""
      publicKey: ""
      sender: ""
    ses:
      region: ""
      sender: ""
  sms:
    type: mock
    twilio:
      accountSid: ""
      authToken: ""
      serviceSid: ""
    nexmo:
      apiKey: ""
      apiSecret: ""
    routemobile:
      username: ""
      password: ""
      source: ""
      region: ""
login:
  loginWith:
    username: false
    phone: true
    email: false
    federated: false
  tfaType: app
  tfaResendTimeout: 0
  allowRegisterMissing: false
keyStorage:
  type: local
  local:
    path: ./jwt/test_artifacts/private.pem
adminPanel:
  enabled: true
loginWebApp:
  type: default
emailTemplaits:
  type: default
# logger settings
logger:
  # logs format (json, text)
  format: json
  # exclude body for HTTP requests that can contain sensitive data
  logSensitiveData: false
  common:
    level: debug
