general: # General server settings.
  port: 8081
  host: http://localhost:8081 # Identifo server URL. If "HOST_NAME" env variable is set, it overrides the value specified here.
  issuer: http://localhost # JWT tokens issuer.

# Names of environment variables that store admin credentials.
adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD

storage:
  appStorage: &dynamo_settings
    type: dynamodb
    dynamo:
      endpoint: http://localhost:8000
      region: us-east-2
  userStorage: *dynamo_settings
  tokenStorage: *dynamo_settings
  tokenBlacklist: *dynamo_settings
  verificationCodeStorage: *dynamo_settings
  inviteStorage: *dynamo_settings

# Storage for admin sessions.
sessionStorage:
  type: memory # Supported values are "memory", "redis", and "dynamodb".
  sessionDuration: 300

keyStorage: # Storage for keys used for signing and verifying JWTs.
  type: local # Key storage type. Supported values are "local" and "s3".
  #file/local key storage settings
  local:
    path: ./jwt/test_artifacts/private.pem

login: # Supported login ways.
  loginWith:
    phone: true
    username: true
    federated: true
  # Type of two-factor authentication, if application enables it.
  # Supported values are: "app" (like Google Authenticator), "sms", "email".
  tfaType: app
  tfaResendTimeout: 30

services:
  email:
    type: mock
  sms:
    type: mock
adminPanel:
  enabled: true
