general: # General server settings.
  port: 8081
  host: http://localhost:8081 # Identifo server URL. If "HOST_NAME" env variable is set, it overrides the value specified here.
  issuer: http://localhost # JWT tokens issuer.

adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD

storage:
  appStorage:
    type: boltdb
    boltdb:
      path: ./db.db
  userStorage:
    type: boltdb
    boltdb:
      path: ./db.db
  tokenStorage:
    type: boltdb
    boltdb:
      path: ./db.db
  tokenBlacklist:
    type: boltdb
    boltdb:
      path: ./db.db
  verificationCodeStorage:
    type: boltdb
    boltdb:
      path: ./db.db
  inviteStorage:
    type: boltdb
    boltdb:
      path: ./db.db
sessionStorage:
  type: memory
  sessionDuration: 300
static:
  type: local
  local:
    folder: ./static
  serveAdminPanel: true
services:
  email:
    type: mock
  sms:
    type: mock
login:
  loginWith:
    username: true
    phone: true
    email: false
    federated: true
  tfaType: app
keyStorage:
  type: local
  file:
    private_key_path: ./jwt/test_artifacts/private.pem
