general: # General server settings.
  port: 8081
  host: http://localhost:8081 # Identifo server URL. If "HOST_NAME" env variable is set, it overrides the value specified here.
  issuer: http://localhost # JWT tokens issuer.

# Names of environment variables that store admin credentials.
adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD

storage:
  appStorage: &storage_settings
    type: fake
  userStorage: *storage_settings
  tokenStorage: *storage_settings
  tokenBlacklist: *storage_settings
  verificationCodeStorage: *storage_settings
  inviteStorage: *storage_settings
  managementKeysStorage: *storage_settings
# Storage for admin sessions.
sessionStorage:
  type: memory # Supported values are "memory", "redis", and "dynamodb".
  sessionDuration: 300

keyStorage: # Storage for keys used for signing and verifying JWTs.
  type: local # Key storage type. Supported values are "local" and "s3".
  local:
    path: ./jwt/test_artifacts/private.pem

login: # Supported login ways.
  loginWith:
    phone: true
    username: true
    federated: true
  tfaType: app
  tfaResendTimeout: 30

services:
  email:
    type: mock
  sms:
    type: mock
adminPanel:
  enabled: true

# logger settings
logger:
  # dump request body in logs
  dumpRequest: false
  # logs format (json, text)
  format: json
  # exclude body for HTTP requests that can contain sensitive data
  logSensitiveData: false
  common:
    level: info
  api:
    httpDetailing: dump
    level: debug
  admin:
    httpDetailing: dump
    level: debug
  spa:
    httpDetailing: short
    level: debug
