general: # General server settings.
  port: 8081
  host: http://localhost:8081 # Identifo server URL. If "HOST_NAME" env variable is set, it overrides the value specified here.
  issuer: http://localhost:8081 # JWT tokens issuer.
  algorithm: es256 # Algorithm for the token service. Supported values are: "rs256", "es256" and "auto".

# Names of environment variables that store admin credentials.
adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD

storage:
  appStorage: &dynamo_settings
    type: dynamodb
    dynamo:
      endpoint: http://localhost:8000
      region: us-east-2
  userStorage: *dynamo_settings
  tokenStorage: *dynamo_settings
  tokenBlacklist: *dynamo_settings
  verificationCodeStorage: *dynamo_settings
  inviteStorage: *dynamo_settings

# Storage for admin sessions.
sessionStorage:
  type: memory # Supported values are "memory", "redis", and "dynamodb".
  # Admin session duration in seconds.
  # This value specifies the maximum time of inactivity in the admin panel before asking to relogin.
  sessionDuration: 300
  address: # Redis-related setting.
  password: # Redis-related setting.
  db: # Redis-related setting.
  region: # DynamoDB-related setting.
  endpoint: # DynamoDB-related setting. Can be figured out automatically from the region.

keyStorage: # Storage for keys used for signing and verifying JWTs.
  type: local # Key storage type. Supported values are "local" and "s3".
  #file/local key storage settings
  file:
    private_key_path: ./jwt/test_artifacts/private.pem
    public_key_path: ./jwt/test_artifacts/public.pem

static:
  type: local
  local:
    folder: ./static
  serveAdminPanel: true

login: # Supported login ways.
  loginWith:
    phone: true
    username: true
    federated: true
  # Type of two-factor authentication, if application enables it.
  # Supported values are: "app" (like Google Authenticator), "sms", "email".
  tfaType: app

services:
  email:
    type: mock
  sms:
    type: mock
