general: # General server settings.
  port: 8081
  host: http://localhost:8081 # Identifo server URL. If "HOST_NAME" env variable is set, it overrides the value specified here.
  issuer: http://localhost:8081 # JWT tokens issuer.
  algorithm: es256 # Algorithm for the token service. Supported values are: "rs256", "es256" and "auto".

# Names of environment variables that store admin credentials.
adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD

storage:
  appStorage:
    type: fake
  userStorage:
    type: fake
  tokenStorage:
    type: fake
  tokenBlacklist:
    type: fake
  verificationCodeStorage:
    type: fake
  inviteStorage:
    type: fake

# Storage for admin sessions.
sessionStorage:
  type: memory # Supported values are "memory", "redis", and "dynamodb".
  sessionDuration: 300

keyStorage: # Storage for keys used for signing and verifying JWTs.
  type: local # Key storage type. Supported values are "local" and "s3".
  file:
    private_key_path: ./jwt/test_artifacts/private.pem
    public_key_path: ./jwt/test_artifacts/public.pem

static:
  type: local
  local:
    folder: ./static
  serveAdminPanel: true

login: # Supported login ways.
  loginWith:
    phone: true
    username: true
    federated: true
  tfaType: app

services:
  email:
    type: mock
  sms:
    type: mock
