general:
  host: http://localhost:8081
  port: "8081"
  issuer: http://localhost
  supported_scopes: []
adminAccount:
  loginEnvName: IDENTIFO_ADMIN_LOGIN
  passwordEnvName: IDENTIFO_ADMIN_PASSWORD
storage:
  appStorage:
    type: boltdb
    boltdb:
      path: ./data/db.db
    mongo:
      connection: ""
      database: ""
    dynamo:
      region: ""
      endpoint: ""
    plugin:
      cmd: ""
      params: {}
    grpc:
      address: ""
  userStorage:
    type: boltdb
    boltdb:
      path: ./data/db.db
    mongo:
      connection: ""
      database: ""
    dynamo:
      region: ""
      endpoint: ""
    plugin:
      cmd: ./plugins/bin/bolt-user-storage
      params:
        path: ./data/user.db
    grpc:
      address: ""
  tokenStorage:
    type: boltdb
    boltdb:
      path: ./data/db.db
    mongo:
      connection: ""
      database: ""
    dynamo:
      region: ""
      endpoint: ""
    plugin:
      cmd: ""
      params: {}
    grpc:
      address: ""
  tokenBlacklist:
    type: boltdb
    boltdb:
      path: ./data/db.db
    mongo:
      connection: ""
      database: ""
    dynamo:
      region: ""
      endpoint: ""
    plugin:
      cmd: ""
      params: {}
    grpc:
      address: ""
  verificationCodeStorage:
    type: boltdb
    boltdb:
      path: ./data/db.db
    mongo:
      connection: ""
      database: ""
    dynamo:
      region: ""
      endpoint: ""
    plugin:
      cmd: ""
      params: {}
    grpc:
      address: ""
  inviteStorage:
    type: boltdb
    boltdb:
      path: ./data/db.db
    mongo:
      connection: ""
      database: ""
    dynamo:
      region: ""
      endpoint: ""
    plugin:
      cmd: ""
      params: {}
    grpc:
      address: ""
sessionStorage:
  type: memory
  sessionDuration: 300
  redis:
    address: ""
    password: ""
    db: 0
    cluster: false
    prefix: ""
  dynamo:
    region: ""
    endpoint: ""
services:
  email:
    type: mock
    mailgun:
      domain: ""
      privateKey: ""
      publicKey: ""
      sender: ""
    ses:
      region: ""
      sender: ""
  sms:
    type: mock
    twilio:
      accountSid: ""
      authToken: ""
      serviceSid: ""
    nexmo:
      apiKey: ""
      apiSecret: ""
    routemobile:
      username: ""
      password: ""
      source: ""
      region: ""
login:
  loginWith:
    username: false
    phone: false
    email: true
    federated: false
  tfaType: app
  tfaResendTimeout: 0
  allowRegisterMissing: false
keyStorage:
  type: local
  local:
    path: ./jwt/test_artifacts/private.pem
logger:
  dumpRequest: false
adminPanel:
  enabled: true
loginWebApp:
  type: default
emailTemplaits:
  type: default
