version: "2"
services:
    mongo:
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - tayble_mongo_data:/data/db

#this will create named volume: tayble_mongo_data
volumes:
  tayble_mongo_data: