export const RECEIVE_LOGIN_SETTINGS = 'RECEIVE_LOGIN_SETTINGS';
export const RECEIVE_EXTERNAL_SETTINGS = 'RECEIVE_EXTERNAL_SETTINGS';
export const RECEIVE_SESSION_STORAGE_SETTINGS = 'RECEIVE_SESSION_STORAGE_SETTINGS';
export const RECEIVE_STATIC_FILES_SETTINGS = 'RECEIVE_STATIC_FILES_SETTINGS';
export const RECEIVE_GENERAL_SETTINGS = 'RECEIVE_GENERAL_SETTINGS';
export const RECEIVE_CONFIGURATION_STORAGE_SETTINGS = 'RECEIVE_CONFIGURATION_STORAGE_SETTINGS';
export const SETTINGS_CHANGED = 'SETTINGS_CHANGED';
