name: "Go nancy"

on: pull_request

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ["go"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.2
      - name: Get dependencies
        run: go mod download

      - name: WriteGoList
        run: go list -json -mod=readonly -m all > go.list

      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main
