name: Publish to docker hub

on:
#   push:
#     tags:
#       - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number in "v1.2.3" format'
        required: true
      latest:
        description: 'Include latest tag'
        required: false
        default: 'false'
# on:
#   release:
#     types: [published]

jobs:

  testp:
    name: test vars on that
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

  publish:
    name: Docker Hub publish
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Exit if not on master branch
      if: endsWith(github.ref, 'master') == false
      run: exit -1

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: madappgangd/identifo
        tag-sha: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build docker image and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}    
