name: Build and test

# on:
#   push:
#     tags:
#       - 'v*.*.*'
on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Exit if not on master branch
      if: endsWith(github.ref, 'master') == false
      run: exit -1

    
    
    