name: Build and test

on:
  push:
    tags:
      - 'v*.*.*'
# on:
#   release:
#     types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Exit if not on master branch
      if: endsWith(github.ref, 'master') == false
      run: exit -1


    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: madappgangd/identifo

    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: madappgangd/identifo
        context: .
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}        

    
    