const types = {
  FETCH_ACCOUNT_SETTINGS_ATTEMPT: 'FETCH_ACCOUNT_SETTINGS_ATTEMPT',
  FETCH_ACCOUNT_SETTINGS_SUCCESS: 'FETCH_ACCOUNT_SETTINGS_SUCCESS',
  FETCH_ACCOUNT_SETTINGS_FAILURE: 'FETCH_ACCOUNT_SETTINGS_FAILURE',

  POST_ACCOUNT_SETTINGS_ATTEMPT: 'POST_ACCOUNT_SETTINGS_ATTEMPT',
  POST_ACCOUNT_SETTINGS_SUCCESS: 'POST_ACCOUNT_SETTINGS_SUCCESS',
  POST_ACCOUNT_SETTINGS_FAILURE: 'POST_ACCOUNT_SETTINGS_FAILURE',

  RESET_ACCOUNT_ERROR: 'RESET_ACCOUNT_ERROR',
};

export default types;
