const types = {
  FETCH_USERS_ATTEMPT: 'FETCH_USERS_ATTEMPT',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',

  POST_USER_ATTEMPT: 'POST_USER_ATTEMPT',
  POST_USER_SUCCESS: 'POST_USER_SUCCESS',

  ALTER_USER_ATTEMPT: 'ALTER_USER_ATTEMPT',
  ALTER_USER_SUCCESS: 'ALTER_USER_SUCCESS',

  FETCH_USER_BY_ID_ATTEMPT: 'FETCH_USER_BY_ID_ATTEMPT',
  FETCH_USER_BY_ID_SUCCESS: 'FETCH_USER_BY_ID_SUCCESS',

  DELETE_USER_BY_ID_ATTEMPT: 'DELETE_USER_BY_ID_ATTEMPT',
  DELETE_USER_BY_ID_SUCCESS: 'DELETE_USER_BY_ID_SUCCESS',

  RESET_USER_ERROR: 'RESET_USER_ERROR',
  RESET_USER_BY_ID: 'RESET_USER_BY_ID',
};

export default types;
